codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: new
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch:
      default:
        threshold: 0.01
    project:
      default:
        threshold: 0.01
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
